# Generated by Django 3.2.5 on 2021-08-02 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CATEGORY',
            fields=[
                ('id_category_product', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('id_category_vehicle', models.CharField(max_length=10)),
                ('category_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PRODUCT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_product', models.CharField(max_length=10)),
                ('product_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=4, max_digits=9)),
                ('brand', models.CharField(max_length=100)),
                ('availability', models.IntegerField()),
                ('registration_date', models.DateTimeField()),
                ('id_category_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_id_category_product', to='quote.category')),
                ('id_category_vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_id_category_vehicle', to='quote.category')),
            ],
            options={
                'db_table': 'PRODUCT',
            },
        ),
        migrations.CreateModel(
            name='QUOTES',
            fields=[
                ('id_quote', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=200)),
                ('date', models.DateTimeField()),
                ('total', models.DecimalField(decimal_places=4, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='ROLE',
            fields=[
                ('id_role', models.IntegerField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SUPPLIERS',
            fields=[
                ('id_supplier', models.IntegerField(primary_key=True, serialize=False)),
                ('supplier_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('contact_name', models.CharField(max_length=100)),
                ('landline', models.CharField(max_length=10)),
                ('mobile_phone', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='USERS',
            fields=[
                ('id_user', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('idcard', models.CharField(max_length=10)),
                ('name_lastname', models.CharField(max_length=150)),
                ('gender', models.CharField(max_length=1)),
                ('born_date', models.DateTimeField()),
                ('landline', models.CharField(max_length=10)),
                ('movile_phone', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=100)),
                ('user', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('last_access', models.DateTimeField()),
                ('city', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('id_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_id_role', to='quote.role')),
            ],
        ),
        migrations.CreateModel(
            name='QUOTES_DETAILS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('subtotal', models.DecimalField(decimal_places=4, max_digits=9)),
                ('id_product', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_id_product', to='quote.product')),
                ('id_quote', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_id_quote', to='quote.quotes')),
                ('id_supplier', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_id_supplier', to='quote.product')),
            ],
            options={
                'db_table': 'QUOTES_DETAILS',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='id_supplier',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_id_supplier', to='quote.suppliers'),
        ),
        migrations.AddConstraint(
            model_name='quotes_details',
            constraint=models.UniqueConstraint(fields=('id_quote', 'id_product', 'id_supplier'), name='unique_quote_detail'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('id_product', 'id_supplier'), name='unique_product_supplier'),
        ),
    ]
