# Generated by Django 3.2.6 on 2021-09-17 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(db_column='PRICE', decimal_places=3, max_digits=12),
        ),
    ]
