# Generated by Django 3.2.5 on 2021-08-03 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuotesDetails',
            fields=[
                ('id_quote', models.OneToOneField(db_column='ID_QUOTE', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='quote.quotes')),
                ('amount', models.IntegerField(db_column='AMOUNT')),
                ('subtotal', models.DecimalField(db_column='SUBTOTAL', decimal_places=4, max_digits=9)),
            ],
            options={
                'db_table': 'quotes_details',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='quotes',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='suppliers',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'managed': False},
        ),
        migrations.DeleteModel(
            name='QUOTES_DETAILS',
        ),
    ]
