# Generated by Django 3.2.6 on 2021-09-01 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0002_users_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(db_column='PASSWORD', max_length=255),
        ),
    ]
