# Generated by Django 3.2.5 on 2021-08-03 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0002_auto_20210803_1407'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='category',
        ),
        migrations.AlterModelTable(
            name='product',
            table='product',
        ),
        migrations.AlterModelTable(
            name='quotes',
            table='quotes',
        ),
        migrations.AlterModelTable(
            name='role',
            table='role',
        ),
        migrations.AlterModelTable(
            name='suppliers',
            table='suppliers',
        ),
        migrations.AlterModelTable(
            name='users',
            table='users',
        ),
    ]
