# Generated by Django 3.2.6 on 2021-09-29 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0002_alter_product_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='movile_phone',
            new_name='mobile_phone',
        ),
        migrations.AlterField(
            model_name='users',
            name='gender',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], db_column='GENDER', max_length=1),
        ),
    ]
