# Generated by Django 3.2.6 on 2021-10-04 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0003_auto_20210929_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(db_column='CATEGORY_NAME', max_length=100),
        ),
    ]
