# Generated by Django 3.2.6 on 2021-10-14 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0004_alter_category_category_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductFiles',
            fields=[
                ('id_pfiles', models.AutoField(db_column='ID_PFILES', primary_key=True, serialize=False)),
                ('name_pfiles', models.CharField(blank=True, db_column='DESCRIPTION', max_length=200, null=True)),
                ('productfile', models.FileField(upload_to='products/')),
            ],
            options={
                'db_table': 'productfile',
                'managed': True,
            },
        ),
    ]
