# Generated by Django 3.2.6 on 2021-10-24 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0005_productfiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(db_column='PRICE', decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='productfiles',
            name='productfile',
            field=models.FileField(upload_to='productsFiles/'),
        ),
    ]
