# Generated by Django 3.2.6 on 2021-11-21 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0007_auto_20211023_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand_vehicle',
            field=models.CharField(blank=True, db_column='BRAND_VEHICLE', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='model_vehicle',
            field=models.CharField(blank=True, db_column='MODEL_VEHICLE', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='part_number',
            field=models.CharField(blank=True, db_column='PART_NUMBER', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='year_vehicle',
            field=models.CharField(blank=True, db_column='YEAR_VEHICLE', max_length=100, null=True),
        ),
    ]
