# Generated by Django 3.2.6 on 2021-12-07 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0008_auto_20211121_1155'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSupplierJoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_product', models.IntegerField(db_column='ID_PRODUCT')),
                ('product_name', models.CharField(db_column='PRODUCT_NAME', max_length=100)),
                ('price', models.DecimalField(db_column='PRICE', decimal_places=2, max_digits=12)),
                ('brand', models.CharField(blank=True, db_column='BRAND', max_length=100, null=True)),
                ('availability', models.IntegerField(blank=True, db_column='AVAILABILITY', null=True)),
                ('brand_vehicle', models.CharField(blank=True, db_column='BRAND_VEHICLE', max_length=100, null=True)),
                ('model_vehicle', models.CharField(blank=True, db_column='MODEL_VEHICLE', max_length=100, null=True)),
                ('year_vehicle', models.CharField(blank=True, db_column='YEAR_VEHICLE', max_length=100, null=True)),
                ('part_number', models.CharField(blank=True, db_column='PART_NUMBER', max_length=100, null=True)),
                ('id_supplier', models.IntegerField(db_column='ID_SUPPLIER')),
                ('supplier_name', models.CharField(db_column='SUPPLIER_NAME', max_length=100)),
                ('conctact_name', models.CharField(db_column='CONCTACT_NAME', max_length=150)),
                ('mobile_phone', models.CharField(blank=True, db_column='MOBILE_PHONE', max_length=15, null=True)),
                ('address', models.CharField(blank=True, db_column='ADDRESS', max_length=200, null=True)),
                ('city', models.CharField(blank=True, db_column='CITY', max_length=100, null=True)),
                ('province', models.CharField(blank=True, db_column='PROVINCE', max_length=100, null=True)),
                ('country', models.CharField(blank=True, db_column='COUNTRY', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='uploadedFiles',
            fields=[
                ('id_ufiles', models.AutoField(db_column='ID_UFILE', primary_key=True, serialize=False)),
                ('name_file', models.CharField(blank=True, db_column='NAME_FILE', max_length=200, null=True)),
                ('description_file', models.CharField(blank=True, db_column='DESCRIPTION_FILE', max_length=200, null=True)),
                ('uploadedfile', models.FileField(upload_to='uploadedDocuments/')),
            ],
            options={
                'db_table': 'uploadedDocuments',
                'managed': True,
            },
        ),
    ]
