# Generated by Django 3.2.6 on 2021-12-10 18:22

import apps.quote.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0009_productsupplierjoin_uploadedfiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='last_modified',
            field=apps.quote.models.AutoDateTimeField(auto_now=True, db_column='LAST_MODIFIED'),
        ),
        migrations.AlterField(
            model_name='users',
            name='mobile_phone',
            field=models.CharField(db_column='MOBILE_PHONE', max_length=15),
        ),
    ]
